// Illustrative catalog from the supplied design, not confirmed stock or prices.
import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();
const categories = [
  ["duong-trieu", "Cung Đình Đường Triều"],
  ["minh-trieu", "Minh Triều & Cung Phi"],
  ["han-trieu", "Hán Triều Cổ Phong"],
  ["kiem-hiep", "Kiếm Hiệp & Tiên Hiệp"],
  ["dan-quoc", "Dân Quốc Tân Thời"],
];
const rows = [
  [
    "mau-don",
    "TYC-CD01",
    "Cung Trang Mẫu Đơn Phú Quý",
    "Gấm đỏ thẫm tôn nét kiêu sa, dệt gấm sa 4 lớp thêu kim tuyến hoa mẫu đơn phú quý.",
    "banner-1.png",
    450000,
    "duong-trieu",
    "female",
    "available",
    155,
    170,
    45,
    62,
    ["Cung đình", "Quý tộc"],
    ["hairpin", "fan"],
    "Được thuê nhiều",
    "red",
  ],
  [
    "lam-sac",
    "TYC-TH12",
    "Lam Sắc Cửu Vĩ Tiên Nhu",
    "Sắc lam thanh nhã, nhẹ nhàng như mây khói, voan mỏng chuyển màu bay bổng.",
    "banner-3.png",
    380000,
    "kiem-hiep",
    "female",
    "available",
    152,
    168,
    42,
    58,
    ["Tiên hiệp", "Cổ trang"],
    ["hairpin", "fan"],
    "Mẫu mới",
    "green",
  ],
  [
    "thuy-truc",
    "TYC-MT05",
    "Thúy Trúc Minh Triều Phi Phong",
    "Áo choàng thêu tinh xảo, tôn dáng trang nhã kết hợp chân váy Mã Diện lấp lánh.",
    "mong-co.jpg",
    420000,
    "minh-trieu",
    "female",
    "available",
    155,
    172,
    45,
    65,
    ["Cổ phục", "Mùa đông"],
    ["hairpin", "embroidered"],
    "Được yêu thích",
    "gold",
  ],
  [
    "phuong-hoang",
    "TYC-HP03",
    "Phượng Hoàng Vu Phi Hỷ Phục",
    "Hỷ phục gấm đỏ thêu tay nổi Phượng Cửu Thiên, kết hợp mũ Cửu Phượng Quan.",
    "banner-2.png",
    680000,
    "han-trieu",
    "female",
    "advance",
    155,
    168,
    46,
    60,
    ["Hỷ phục cưới", "Hoàng gia"],
    ["hairpin", "embroidered"],
    "Hỷ Phục Đại Lễ",
    "red",
  ],
  [
    "bich-ngoc",
    "TYC-DQ02",
    "Bích Ngọc Dân Quốc Kỳ Bào",
    "Vải nhung xanh ngọc bích cao cấp may phom chuẩn tôn dáng, nút thắt cổ điển.",
    "logo.png",
    290000,
    "dan-quoc",
    "female",
    "available",
    158,
    170,
    46,
    56,
    ["Dân Quốc", "Sườn xám"],
    ["fan"],
    "Được yêu thích",
    "green",
  ],
  [
    "nguyet-ha",
    "TYC-KH08",
    "Nguyệt Hạ Độc Hành Đạo Bào",
    "Lụa gấm dệt trúc trầm mặc, kèm bao hộ cổ tay kiếm sĩ và đai lưng khắc hoa văn.",
    "logo.png",
    350000,
    "kiem-hiep",
    "male",
    "available",
    168,
    182,
    55,
    78,
    ["Hào kiệt", "Đạo bào"],
    ["sword"],
    "Kiếm Hiệp Nam Y",
    "green",
  ],
  ["van-lien", "TYC-DT07", "Vân Liên Đường Triều", "Trang phục mẫu sắc hồng dịu, tay áo mềm rủ phối chân váy nhiều lớp cho concept cung đình.", "banner-1.png", 460000, "duong-trieu", "female", "available", 153, 170, 43, 62, ["Đường triều", "Cung đình"], ["hairpin", "fan"], "Mẫu mới", "red"],
  ["thanh-phong", "TYC-KH09", "Thanh Phong Kiếm Khách", "Đạo bào mẫu dáng suông, phối đai lưng gọn gàng và kiếm cho concept kiếm khách cổ phong.", "banner-3.png", 390000, "kiem-hiep", "unisex", "available", 165, 185, 52, 80, ["Kiếm hiệp", "Cổ phong"], ["sword"], "Mẫu mới", "green"],
  ["hong-lien", "TYC-HT06", "Hồng Liên Hán Phục", "Hán phục mẫu tông đỏ ấm, tay áo rộng và đường thêu hoa phù hợp chụp ảnh cổ trang.", "banner-2.png", 520000, "han-trieu", "female", "advance", 155, 173, 45, 65, ["Hán phục", "Thêu hoa"], ["hairpin", "embroidered"], "Mẫu mới", "red"],
  ["ngoc-diep", "TYC-MT08", "Ngọc Điệp Minh Triều", "Trang phục mẫu phối áo choàng và chân váy dài, điểm hoa văn trang nhã cho concept Minh triều.", "mong-co.jpg", 430000, "minh-trieu", "female", "available", 150, 168, 42, 60, ["Minh triều", "Cổ phục"], ["fan", "embroidered"], "Mẫu mới", "gold"],
];
async function main() {
  for (const [position, [slug, name]] of categories.entries())
    await db.productCategory.upsert({
      where: { slug },
      create: { slug, name, position },
      update: {},
    });
  for (const [i, r] of rows.entries()) {
    const [
      slug,
      code,
      name,
      description,
      image,
      price,
      categorySlug,
      gender,
      availability,
      minHeight,
      maxHeight,
      minWeight,
      maxWeight,
      tags,
      accessories,
      badge,
      badgeTone,
    ] = r;
    await db.costumeProduct.upsert({
      where: { slug },
      update: {},
      create: {
        slug,
        code,
        name,
        description,
        image: "/images/" + image,
        price,
        categorySlug,
        gender,
        availability,
        minHeight,
        maxHeight,
        minWeight,
        maxWeight,
        tags,
        accessories,
        badge,
        badgeTone,
        popularity: 100 - i,
      },
    });
  }
}
main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
