"use client";
import { useEffect, useState } from "react";
import AdminShell, { buttonStyle, inputStyle, primaryStyle } from "./admin-shell";
import ToastViewport, {type ToastItem} from "./toast";
import { apiFetch } from "@/lib/api-fetch";
import { Icon } from "../icon";
type User = {email:string;name:string;role:"admin"|"manager";active:boolean};
export default function AdminUsers() {
 const [users,setUsers]=useState<User[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[toast,setToast]=useState<ToastItem|null>(null),[allowed,setAllowed]=useState(false);
 const [form,setForm]=useState({name:"",email:"",password:""});
 useEffect(()=>{const abort=new AbortController();setLoading(true);apiFetch('/api/admin/users',{signal:abort.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error?.message||"Không tải được người dùng.");setUsers(b.data);setAllowed(true);setError("");}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[reload]);
 async function save(body:object,method:"POST"|"PATCH") {setBusy(true);setError("");try{const r=await apiFetch('/api/admin/users',{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error?.message||"Không lưu được người dùng.");setReload(n=>n+1);setToast({id:crypto.randomUUID(),tone:"success",message:method==="POST"?"Đã tạo tài khoản nội bộ.":"Đã cập nhật trạng thái tài khoản."});if(method==="POST"){setForm({name:"",email:"",password:""});setShow(false);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <AdminShell title="Người dùng" actions={allowed ? (<button type="button" onClick={()=>setShow(!show)} className={primaryStyle}><Icon name="users"/>Tạo tài khoản</button>) : undefined}><ToastViewport items={toast?[toast]:[]} onDismiss={()=>setToast(null)}/><div className="mb-6 grid gap-4 sm:grid-cols-3">{[{label:"Tổng người dùng",value:users.length},{label:"Tài khoản hoạt động",value:users.filter(u=>u.active).length},{label:"Quản lý",value:users.filter(u=>u.role==="manager").length}].map(s=><div key={s.label} className="rounded-md border border-stone-200 bg-white p-5"><p className="text-sm text-stone-500">{s.label}</p><p className="mt-2 text-3xl font-semibold text-[#781216]">{loading?"—":s.value}</p></div>)}</div>
 {error&&<p role="alert" className="mb-4 text-red-800">{error}</p>}
 {allowed&&<section className="rounded-md border border-stone-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-[#781216]">Người dùng nội bộ</h2><div className="flex flex-wrap gap-3"><input type="search" aria-label="Tìm người dùng" placeholder="Tìm tên / email…" value={search} onChange={e=>setSearch(e.target.value)} className={`${inputStyle} !mt-0 !w-64`}/></div></div><p className="mt-4 rounded-md bg-stone-50 p-3 text-sm text-stone-500">Chỉ dành cho nhân sự nội bộ. Quản lý được sử dụng các màn quản trị kinh doanh; chỉ Admin được quản lý tài khoản.</p>
 {show&&<form onSubmit={e=>{e.preventDefault();void save(form,"POST");}} className="mt-5 grid gap-4 rounded-md border border-stone-200 p-4 sm:grid-cols-3"><label className="text-sm">Họ tên *<input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={inputStyle}/></label><label className="text-sm">Email *<input type="email" required maxLength={191} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className={inputStyle}/></label><label className="text-sm">Mật khẩu *<input type="password" required minLength={10} maxLength={72} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className={inputStyle}/></label><div className="flex gap-2 sm:col-span-3"><button disabled={busy} className={primaryStyle}>{busy?"Đang tạo…":"Tạo tài khoản quản lý"}</button><button type="button" onClick={()=>setShow(false)} className={buttonStyle}>Bỏ qua</button></div></form>}
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-stone-50 text-stone-500"><tr>{["Họ tên","Email","Vai trò","Trạng thái","Thao tác"].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead><tbody>{users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(search.trim().toLowerCase())).map(u=><tr key={u.email} className="border-b border-stone-100"><td className="p-3 font-medium">{u.name}</td><td className="p-3">{u.email}</td><td className="p-3">{u.role==="admin"?"Quản trị viên":"Quản lý"}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs ${u.active?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{u.active?"Hoạt động":"Đã khóa"}</span></td><td className="p-3">{u.role==="admin"?<span className="text-xs text-stone-400">Tài khoản hệ thống</span>:<button disabled={busy} type="button" className={buttonStyle} onClick={()=>void save({email:u.email,active:!u.active},"PATCH")}>{u.active?"Khóa":"Mở khóa"}</button>}</td></tr>)}</tbody></table>{!loading&&!users.some(u=>`${u.name} ${u.email}`.toLowerCase().includes(search.trim().toLowerCase()))&&<p className="p-6 text-center text-sm text-stone-500">Không tìm thấy người dùng.</p>}</div></section>}
 </AdminShell>;
}
