"use client";
import { useEffect, useRef, useState } from "react";
import AdminSelect from "./admin-select";
import { Icon } from "../icon";
import { buttonStyle, primaryStyle } from "./admin-shell";
export type DateRange = { start: string; end: string };
export const localToday = () => new Intl.DateTimeFormat("en-CA", {timeZone:"Asia/Ho_Chi_Minh", year:"numeric", month:"2-digit", day:"2-digit"}).format(new Date());
const iso = (d: Date) => d.toISOString().slice(0,10);
const display = (s: string) => s ? s.split("-").reverse().join("/") : "--/--/----";
const options = [{value:"today",label:"Hôm nay"},{value:"yesterday",label:"Hôm qua"},{value:"week",label:"7 ngày qua"},{value:"month",label:"Tháng này"},{value:"lastMonth",label:"Tháng trước"},{value:"custom",label:"Tùy chỉnh"}];
export default function DashboardDateFilter({range,onChange,onRefresh,updated,actions}: {range:DateRange;onChange:(r:DateRange)=>void;onRefresh:()=>void;updated:string;actions?:React.ReactNode}) {
 const [preset,setPreset]=useState("today"), [open,setOpen]=useState(false), [draft,setDraft]=useState(range), [month,setMonth]=useState(range.start.slice(0,7));
 const root=useRef<HTMLDivElement>(null), trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{ if(!open)return; const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);}; const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);trigger.current?.focus();}};document.addEventListener("pointerdown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",escape);};},[open]);
 function choose(value:string) {setPreset(value); const today=localToday();const date=new Date(today+"T00:00:00Z");let start=today,end=today;
 if(value==="custom"){setDraft(range);setMonth(range.start.slice(0,7));setOpen(true);return;}
 if(value==="yesterday"){date.setUTCDate(date.getUTCDate()-1);start=end=iso(date);}
 if(value==="week"){date.setUTCDate(date.getUTCDate()-6);start=iso(date);}
 if(value==="month")start=today.slice(0,7)+"-01";
 if(value==="lastMonth"){date.setUTCDate(0);end=iso(date);date.setUTCDate(1);start=iso(date);}
 setOpen(false);onChange({start,end}); }
 function shift(n:number){const d=new Date(month+"-01T00:00:00Z");d.setUTCMonth(d.getUTCMonth()+n);setMonth(iso(d).slice(0,7));}
 function pick(date:string){setDraft(prev=> !prev.start||prev.end ? {start:date,end:""} : date<prev.start?{start:date,end:prev.start}:{...prev,end:date});}
 const valid=!!draft.start&&!!draft.end&&draft.start<=draft.end&&(Date.parse(draft.end)-Date.parse(draft.start))/86400000<=730;
 return <div ref={root}><div className="relative flex flex-wrap justify-end gap-3"><AdminSelect ariaLabel="Khoảng thời gian thống kê" value={preset} options={options} onChange={choose} className="w-44"/><button ref={trigger} type="button" aria-expanded={open} onClick={()=>{setDraft(range);setMonth(range.start.slice(0,7));setOpen(!open);}} className={`${buttonStyle} min-w-64 justify-between`}><span>{preset==="custom"?`${display(range.start)} – ${display(range.end)}`:"Chọn khoảng ngày"}</span><Icon name="calendar"/></button><button type="button" onClick={onRefresh} className={buttonStyle}><Icon name="reset"/>Làm mới</button>{actions}
 {open&&<div role="dialog" aria-label="Chọn khoảng ngày thống kê" className="absolute right-0 top-full z-30 mt-2 w-[min(680px,calc(100vw-48px))] overflow-hidden rounded-xl border border-[#e7e6e9] bg-white shadow-xl"><div className="flex flex-wrap gap-3 border-b border-stone-200 p-4 text-sm"><label>Từ <input type="date" aria-label="Ngày bắt đầu" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})} className="rounded border border-stone-200 p-1"/></label><label>Đến <input type="date" aria-label="Ngày kết thúc" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})} className="rounded border border-stone-200 p-1"/></label></div><div className="grid sm:grid-cols-2">{[0,1].map(index=>{const date=new Date(month+"-01T00:00:00Z");date.setUTCMonth(date.getUTCMonth()+index);const y=date.getUTCFullYear(),m=date.getUTCMonth(),days=new Date(Date.UTC(y,m+1,0)).getUTCDate(),padding=(date.getUTCDay()+6)%7;return <div key={index} className="border-stone-200 p-4 sm:first:border-r"><div className="mb-3 flex items-center justify-between"><button type="button" aria-label={index?"Tháng sau":"Tháng trước"} onClick={()=>shift(index?1:-1)} className={`${buttonStyle} !px-2`}><Icon name="chevron" className={index?"":"rotate-180"}/></button><strong className="text-sm">Tháng {m+1} {y}</strong><span className="w-8"/></div><div className="grid grid-cols-7 gap-1 text-center text-sm">{["T2","T3","T4","T5","T6","T7","CN"].map(d=><span key={d} className="py-2 text-xs text-stone-500">{d}</span>)}{Array.from({length:padding},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:days},(_,i)=>{const day=iso(new Date(Date.UTC(y,m,i+1))),edge=day===draft.start||day===draft.end,inside=draft.start&&draft.end&&day>draft.start&&day<draft.end;return <button key={day} type="button" aria-label={display(day)} aria-pressed={edge} onClick={()=>pick(day)} className={`h-9 rounded-md text-sm transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#781216] ${edge?"border border-[#b8872e] bg-[#781216] text-white":inside?"bg-[#fcf0ed] text-[#781216]":"hover:bg-[#fcf0ed]"}`}>{i+1}</button>;})}</div></div>;})}</div><div className="flex items-center justify-between border-t border-stone-200 bg-stone-50 p-4"><button type="button" onClick={()=>{const t=localToday();setDraft({start:t,end:t});setMonth(t.slice(0,7));}} className="text-sm font-semibold text-[#781216]">Hôm nay</button><div className="flex gap-2"><button type="button" onClick={()=>setOpen(false)} className={buttonStyle}>Bỏ qua</button><button type="button" disabled={!valid} onClick={()=>{onChange(draft);setPreset("custom");setOpen(false);trigger.current?.focus();}} className={`${primaryStyle} disabled:opacity-40`}>Áp dụng</button></div></div>{draft.start&&draft.end&&!valid&&<p role="alert" className="px-4 pb-3 text-xs text-red-800">Chọn ngày kết thúc sau ngày bắt đầu, tối đa 2 năm.</p>}</div>}
 </div><p className="mt-3 text-right text-xs text-stone-500">{display(range.start)} – {display(range.end)}{updated&&` · Cập nhật lúc ${updated}`}</p></div>;
}
