CREATE TABLE IF NOT EXISTS InternalUser (
 email VARCHAR(191) NOT NULL PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 passwordHash VARCHAR(255) NOT NULL,
 sessionVersion VARCHAR(64) NOT NULL DEFAULT '',
 active TINYINT(1) NOT NULL DEFAULT 1,
 createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
