import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { createHmac, randomBytes, randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import net from 'node:net';

// DB_USER needs CREATE/DROP DATABASE on a disposable local/CI database server.
const privateDir = await mkdtemp(path.join(tmpdir(), 'tyc-php-test-'));
const env = { ...process.env, DB_NAME: `tyc_test_${randomBytes(6).toString('hex')}`, TYC_PRIVATE_DIR: privateDir, APP_ENV: 'development' };
env.PAYOS_CLIENT_ID='test-only'; env.PAYOS_API_KEY='test-only'; env.PAYOS_CHECKSUM_KEY='isolated-webhook-test-key';
const php = process.env.PHP_BINARY || 'php';
function setup(action, ...args) {
  const result = spawnSync(php, ['scripts/php-test-database.php', action, ...args], { env, encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr + result.stdout);
}
async function port() {
  const socket = net.createServer();
  await new Promise(resolve => socket.listen(0, '127.0.0.1', resolve));
  const value = socket.address().port;
  await new Promise(resolve => socket.close(resolve));
  return value;
}
const servers = [];
try {
  const validation = spawnSync(php, ['scripts/test-php-validation.php'], { encoding: 'utf8' });
  assert.equal(validation.status, 0, validation.stderr + validation.stdout);
  setup('create');
  const ports = [await port(), await port()];
  const base = `http://127.0.0.1:${ports[0]}`;
  env.APP_ORIGIN = base;
  for (const p of ports) {
    const serverEnv=p===ports[1]?{...env,PAYOS_CLIENT_ID:'',PAYOS_API_KEY:'',PAYOS_CHECKSUM_KEY:''}:env;
    const server = spawn(php, ['-S', `127.0.0.1:${p}`, '-t', 'public', 'scripts/php-router.php'], { env:serverEnv, stdio: 'ignore' });
    servers.push(server);
  }
  for (const p of ports) {
    let ready = false;
    for (let i = 0; i < 60; i++) {
      try { ready = (await fetch(`http://127.0.0.1:${p}/api/health`)).ok; } catch { /* wait for server */ }
      if (ready) break;
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    assert.ok(ready, 'PHP server started');
  }
  let cookie = '';
  async function request(url, method = 'GET', body, expected = 200, options = {}) {
    const r = await fetch((options.base || base) + url, { method, headers: {
      'Content-Type': 'application/json', Origin: options.origin ?? base, Cookie: options.anonymous ? '' : cookie,
    }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    const text = await r.text();
    assert.equal(r.status, expected, `${method} ${url}: ${text}`);
    return { body: text ? JSON.parse(text) : null, response: r };
  }
  await request('/api/ready');
  await request('/api/products?sort=');
  await request('/api/admin/products', 'GET', undefined, 401);
  await request('/api/admin/categories', 'GET', undefined, 401);
  await request('/api/auth/session', 'GET', undefined, 401);
  await request('/api/products', 'POST', {}, 405);
  await request('/api/products/availability?slug=no-such-product', 'GET', undefined, 404);
  await request('/api/auth/session', 'POST', { identifier: 'test@example.com', password: 'wrong' }, 401);
  const login = await request('/api/auth/session', 'POST', { identifier: 'test@example.com', password: 'local-test-password' });
  const setCookie = login.response.headers.get('set-cookie');
  assert.match(setCookie, /HttpOnly/i); assert.match(setCookie, /SameSite=Lax/i);
  cookie = setCookie.split(';')[0];
  assert.equal((await request('/api/auth/session')).body.data.email, 'test@example.com');
  const adminCookie = cookie;
  const manager = {email:'manager@example.com',name:'Test Manager',password:'local-test-password'};
  await request('/api/admin/users','POST',manager,403,{origin:'https://attacker.example'});
  await request('/api/admin/users','POST',manager);
  await request('/api/admin/users','POST',manager,409);
  assert.ok((await request('/api/admin/users')).body.data.every(row=>!('passwordHash' in row)));
  const managerLogin = await request('/api/auth/session','POST',{identifier:manager.email,password:manager.password},200,{anonymous:true});
  assert.equal(managerLogin.body.data.role,'manager');
  const managerCookie=managerLogin.response.headers.get('set-cookie').split(';')[0];cookie=managerCookie;
  await request('/api/admin/products');
  await request('/api/admin/users','GET',undefined,403);
  await request('/api/admin/users','POST',{...manager,email:'escalation@example.com'},403);
  cookie=adminCookie;
  await request('/api/admin/users','PATCH',{email:manager.email,active:false});
  cookie=managerCookie;await request('/api/auth/session','GET',undefined,401);
  cookie=adminCookie;await request('/api/admin/users','PATCH',{email:manager.email,active:true});
  cookie=managerCookie;await request('/api/auth/session','GET',undefined,401);
  cookie=adminCookie;
  await request('/api/admin/users','PATCH',{email:'test@example.com',active:false},409);
  const category = { slug: 'test-category', name: 'Danh mục thử', codePrefix: 'ZZ', position: 9 };
  await request('/api/admin/categories', 'POST', category, 403, { origin: 'https://attacker.example' });
  await request('/api/admin/categories', 'POST', category, 201);
  const categoryOrder = (await request('/api/admin/categories')).body.data.map(row => row.slug);
  assert.equal(categoryOrder[0], category.slug, 'new category must be first');
  await request('/api/admin/categories', 'PATCH', {order: [...categoryOrder].reverse()});
  assert.deepEqual((await request('/api/admin/categories')).body.data.map(row => row.slug), [...categoryOrder].reverse());
  await request('/api/admin/categories', 'PATCH', {order: categoryOrder.slice(1)}, 409);
  await request('/api/admin/categories', 'PATCH', {order: [category.slug, category.slug]}, 422);
  await request('/api/admin/categories', 'POST', {...category, slug: 'duplicate-prefix'}, 409);
  await request('/api/admin/categories', 'PATCH', {...category, name: 'Danh mục đã sửa'});
  assert.ok((await request('/api/product-categories')).body.data.some(row => row.name === 'Danh mục đã sửa'));
  await request('/api/admin/categories', 'DELETE', {slug:'duong-trieu'}, 409);
  await request('/api/admin/categories', 'DELETE', {slug:category.slug});
  await request('/api/admin/products', 'DELETE', { codes: ['PHP-TEST'] }, 403, { origin: 'https://attacker.example' });
  const product = {code:'PHP-TEST',slug:'php-test',name:'PHP test product',description:'Test',price:300000,category:'Cổ phục',gender:'Nữ',status:'Sẵn sàng',tags:'test',accessories:'fan',badge:'Mẫu mới',minHeight:150,maxHeight:175,minWeight:40,maxWeight:70,published:true,images:['/images/logo.png','/images/banner-1.png']};
  await request('/api/admin/products/publication', 'PATCH', product);
  await request('/api/admin/categories', 'POST', category, 201);
  const categoryProduct = {...product, code:'ZZ-TEST', slug:'category-test', category:category.name};
  const createdProduct = await request('/api/admin/products', 'POST', categoryProduct);
  assert.equal(createdProduct.body.data.categoryName, category.name, 'create response includes the current category');
  assert.equal((await request('/api/admin/products')).body.data[0].code, 'ZZ-TEST', 'new products lead the admin list');
  assert.equal((await request('/api/products/category-test')).body.data.code, 'ZZ-TEST', 'published creation is visible to customers');
  await request('/api/admin/products', 'POST', categoryProduct, 409);
  await request('/api/admin/categories', 'DELETE', {slug:category.slug}, 409);
  await request('/api/admin/categories', 'PATCH', {...category, name:'Tên danh mục mới'});
  assert.equal((await request('/api/admin/products')).body.data.find(row => row.code === 'ZZ-TEST').categoryName, 'Tên danh mục mới');
  await request('/api/admin/products', 'DELETE', {codes:['ZZ-TEST']});
  await request('/api/admin/categories', 'DELETE', {slug:category.slug});
  assert.equal((await request('/api/products/php-test')).body.data.images.length, 2);
  const updatedProduct = await request('/api/admin/products', 'PATCH', {...product,popularity:100,likes:50,rating:4.5,reviewCount:40});
  assert.equal(updatedProduct.body.data.categoryName, 'Minh Triều & Cung Phi', 'save response includes the current category');
  const stats = (await request('/api/products/php-test')).body.data;
  assert.deepEqual([stats.popularity,stats.likes,stats.rating,stats.reviewCount],[100,50,4.5,40]);
  await request('/api/admin/products', 'PATCH', {...product,rating:6},422);
  await request('/api/admin/products', 'PATCH', {...product,likes:-1},422);
  await request('/api/admin/products', 'PATCH', {...product,name:'Saved name'});
  await request('/api/admin/products/publication', 'PATCH', {...product,published:false});
  await request('/api/products/php-test','GET',undefined,404);
  await request('/api/admin/products/publication', 'PATCH', product);
  assert.equal((await request('/api/products/php-test')).body.data.name, 'Saved name', 'publication must not overwrite product');
  await request('/api/admin/products', 'PATCH', {...product,images:['/uploads/../secret.php']},422);
  const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jF1kAAAAASUVORK5CYII=';
  const upload=(await request('/api/admin/uploads','POST',{image:png},201)).body.data.url;
  async function multipartUpload(bytes, type, expected, options = {}) {
    const form = new FormData();
    form.set('image', new Blob([bytes], {type}), 'photo.webp');
    const response = await fetch(base + '/api/admin/uploads', {method:'POST',headers:{Origin:options.origin ?? base,Cookie:options.anonymous?'':cookie},body:form});
    const text = await response.text();
    assert.equal(response.status, expected, text);
    return JSON.parse(text);
  }
  const pngBytes = Buffer.from(png.split(',')[1], 'base64');
  const multipart = await multipartUpload(pngBytes, 'image/png', 201);
  assert.match(multipart.data.url, /^\/uploads\/[a-f0-9-]+\.png$/);
  const servedPhoto = await fetch(base + multipart.data.url);
  assert.deepEqual(Buffer.from(await servedPhoto.arrayBuffer()), pngBytes);
  await multipartUpload(pngBytes, 'image/png', 401, {anonymous:true});
  await multipartUpload(pngBytes, 'image/png', 403, {origin:'https://attacker.example'});
  await multipartUpload(Buffer.from('<?php echo 1;'), 'image/png', 422);
  await multipartUpload(Buffer.alloc(750001), 'image/png', 422);
  const image=await fetch(base+upload);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');
  const components = {components:'Mũ Mông Cổ\nTrang sức Mông Cổ',componentImages:[upload,'']};
  await request('/api/admin/products','PATCH',{...product,...components});
  const savedComponents = (await request('/api/products/php-test')).body.data;
  assert.equal(savedComponents.components, components.components);
  assert.deepEqual(savedComponents.componentImages, components.componentImages);
  assert.deepEqual((await request('/api/admin/products')).body.data.find(row=>row.code===product.code).componentImages, components.componentImages);
  await request('/api/admin/products','PATCH',{...product,...components,componentImages:['/uploads/../secret.php','']},422);
  await request('/api/admin/products','PATCH',{...product,...components,componentImages:[]},422);
  await request('/api/admin/products','PATCH',{...product,components:'',componentImages:[]});
  assert.deepEqual((await request('/api/products/php-test')).body.data.componentImages, []);
  await request('/api/admin/uploads','POST',{image:'data:image/png;base64,PD9waHAgZXZpbA=='},422);
  const date=new Date(Date.now()+86400000*2).toISOString().slice(0,10);
  const rental={id:randomUUID(),productSlug:'php-test',name:'Test customer',phone:'0901234567',start:date,end:date,height:'160',weight:'50',note:''};
  await request('/api/admin/products','PATCH',{...product,price:450000,extraDay:50000,deposit:50000,accessoryFee:0});
  await request('/api/rental-requests','POST',rental,201);
  const savedQuote=(await request('/api/admin/rental-requests?requestId='+rental.id)).body.data[0].priceSnapshot;
  assert.equal(savedQuote.total,450000); assert.equal(savedQuote.remaining,400000);
  await request('/api/admin/products','PATCH',{...product,price:600000,extraDay:70000,deposit:100000,accessoryFee:20000});
  assert.deepEqual((await request('/api/admin/rental-requests?requestId='+rental.id)).body.data[0].priceSnapshot,savedQuote);
  await request('/api/admin/products','PATCH',{...product,deposit:9999999},422);
  await request('/api/rental-requests','POST',rental,201);
  await request('/api/rental-requests','POST',{...rental,name:'Different'},409);
  const other={...rental,id:randomUUID(),phone:'0901234568'};
  await request('/api/rental-requests','POST',other,201);
  const confirmations=await Promise.all([rental,other].map((row,i)=>fetch(`http://127.0.0.1:${ports[i]}/api/admin/rental-requests`,{method:'PATCH',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:JSON.stringify({id:row.id,action:'confirm'})})));
  assert.deepEqual(confirmations.map(r=>r.status).sort(),[200,409], 'concurrent confirmations cannot double book');
  const winner=confirmations[0].status===200?rental:other;
  assert.deepEqual((await request('/api/products/availability?slug=php-test')).body.data,[{start:date,end:date}]);
  await request('/api/rental-requests','POST',{...rental,id:randomUUID()},409);
  const list=(await request('/api/admin/rental-requests?page=999')).body;
  assert.equal(list.total,2);assert.equal(list.page,1);assert.match(list.data[0].createdAt,/Z$/);
  const rentalStatus = async () => (await request('/api/admin/products')).body.data.find(row => row.code === 'PHP-TEST').rentalStatus;
  assert.equal(await rentalStatus(), 'rented');
  assert.equal((await request('/api/products/php-test')).body.data.availability, 'rented');
  assert.ok((await request('/api/products?availability=rented')).body.data.some(row => row.code === 'PHP-TEST'));
  assert.ok(!(await request('/api/products?availability=available')).body.data.some(row => row.code === 'PHP-TEST'));
  const laterDate = new Date(Date.now()+86400000*7).toISOString().slice(0,10);
  const later = {...rental, id:randomUUID(), start:laterDate, end:laterDate, phone:'0901234599'};
  await request('/api/rental-requests','POST',later,201);
  await request('/api/admin/rental-requests','PATCH',{id:later.id,action:'return'},409);
  await request('/api/admin/rental-requests','PATCH',{id:later.id,action:'confirm'});
  const returned = (await request('/api/admin/rental-requests','PATCH',{id:winner.id,action:'return'})).body.data;
  assert.equal(returned.status,'completed'); assert.match(returned.returnedAt,/Z$/);
  assert.equal((await request('/api/admin/rental-requests','PATCH',{id:winner.id,action:'return'})).body.data.returnedAt,returned.returnedAt);
  await request('/api/admin/rental-requests','PATCH',{id:winner.id,action:'cancel'},409);
  assert.equal(await rentalStatus(),'rented','other confirmed booking keeps product rented');
  assert.deepEqual((await request('/api/products/availability?slug=php-test')).body.data,[{start:laterDate,end:laterDate}]);
  await request('/api/rental-requests','POST',{...rental,id:randomUUID(),phone:'0901234588'},201);
  await request('/api/admin/rental-requests','PATCH',{id:later.id,action:'cancel'});
  assert.equal(await rentalStatus(),'ready');
  assert.equal((await request('/api/products/php-test')).body.data.availability, 'available');
  assert.deepEqual((await request('/api/products/availability?slug=php-test')).body.data,[]);
  await request('/api/admin/rental-requests','PATCH',{id:winner.id,action:'confirm'},409);
  await request('/api/admin/products','DELETE',{codes:['PHP-TEST']});
  await request('/api/products/php-test','GET',undefined,404);
  await request('/api/admin/products','POST',{...product,published:false});
  const manual = {...rental,id:randomUUID(),start:laterDate,end:laterDate};
  await request('/api/admin/rental-requests','POST',manual,401,{anonymous:true});
  await request('/api/admin/rental-requests','POST',manual,403,{origin:'https://attacker.example'});
  await request('/api/rental-requests','POST',manual,404);
  await request('/api/admin/rental-requests','POST',manual,201);
  await request('/api/admin/rental-requests','POST',manual,201);
  const manualRows=(await request('/api/admin/rental-requests?requestId='+manual.id)).body.data;
  assert.equal(manualRows.length,1,'retry does not duplicate a manual order');
  assert.equal(manualRows[0].status,'pending');
  await request('/api/admin/rental-requests','PATCH',{id:manual.id,action:'confirm'});
  assert.equal((await request('/api/admin/rental-requests?productCode='+product.code)).body.data.length,1,'manual confirmation appears in product calendar');
  await request('/api/admin/rental-requests','POST',{...manual,id:randomUUID()},409);
  await request('/api/admin/rental-requests','PATCH',{id:manual.id,action:'cancel'});
  await request('/api/admin/products/publication','PATCH',{...product,published:true});
  await request('/api/admin/products','PATCH',{...product,deposit:50000});
  const zeroProduct={...product,code:'ZERO-TEST',slug:'zero-test',deposit:0};
  await request('/api/admin/products','POST',zeroProduct);
  const checkout={...rental,id:randomUUID(),token:randomBytes(32).toString('hex'),method:'bank_transfer',phone:'0907654321',items:[{productSlug:'php-test',start:laterDate,end:laterDate},{productSlug:'zero-test',start:laterDate,end:laterDate}],amount:1,total:1};
  const payment=(await request('/api/checkout','POST',checkout)).body.data;
  const disabledBase=`http://127.0.0.1:${ports[1]}`;
  assert.equal((await request('/api/checkout','GET',undefined,200,{base:disabledBase})).body.enabled,false);
  await request('/api/checkout','POST',{...checkout,id:randomUUID(),phone:'0907654333',method:'payos'},503,{base:disabledBase});
  assert.equal(payment.state,'manual'); assert.equal(payment.amount,50000); assert.equal(payment.total,600000);
  assert.equal(payment.bank.name,'BIDV'); assert.equal(payment.bank.holder,'Phạm Gia Tiến'); assert.equal(payment.bank.account,'7411028927');
  assert.equal((await request('/api/checkout','POST',checkout)).body.data.items[0].id,payment.items[0].id,'checkout retry reuses rental IDs');
  await request('/api/checkout','POST',{...checkout,name:'Changed'},409);
  await request('/api/checkout','POST',{...checkout,id:randomUUID()},403,{origin:'https://attacker.example'});
  await request('/api/checkout/lookup','POST',{id:checkout.id,token:'0'.repeat(64)},404);
  await request('/api/checkout','POST',{...checkout,id:randomUUID(),items:[checkout.items[0],checkout.items[0]]},422);
  setup('payment-fixture',checkout.id);
  await request('/api/rental-requests','POST',{...rental,id:randomUUID(),start:laterDate,end:laterDate},409);
  const online=payment.items.find(i=>i.productSlug==='php-test');
  await request('/api/admin/rental-requests','PATCH',{id:online.id,action:'confirm'},409);
  const sign=data=>createHmac('sha256',env.PAYOS_CHECKSUM_KEY).update(Object.keys(data).sort().map(k=>`${k}=${data[k]}`).join('&')).digest('hex');
  const event={orderCode:Number(payment.transferContent.slice(4)),amount:payment.amount,currency:'VND',code:'00',reference:'test-payment-1'};
  await request('/api/payments/webhook','POST',{data:event,signature:'0'.repeat(64)},401);
  await request('/api/payments/webhook','POST',{data:event,signature:[]},401);
  const badAmount={...event,amount:1};await request('/api/payments/webhook','POST',{data:badAmount,signature:sign(badAmount)},422);
  await request('/api/payments/webhook','POST',{data:event,signature:sign(event)});
  await request('/api/payments/webhook','POST',{data:event,signature:sign(event)});
  const paid=(await request('/api/checkout/lookup','POST',{id:checkout.id,token:checkout.token})).body.data;
  assert.equal(paid.state,'paid');assert.equal(paid.items.find(i=>i.productSlug==='php-test').status,'confirmed');
  assert.equal(paid.items.find(i=>i.productSlug==='zero-test').status,'pending','zero deposit requires store confirmation');
  const secondEvent={...event,reference:'test-payment-2'};await request('/api/payments/webhook','POST',{data:secondEvent,signature:sign(secondEvent)},409);
  await request('/api/admin/rental-requests','PATCH',{id:online.id,action:'cancel'});
  const lateCheckout={...checkout,id:randomUUID(),phone:'0907654322',items:[checkout.items[0]]};
  const late=(await request('/api/checkout','POST',lateCheckout)).body.data;setup('payment-fixture',lateCheckout.id,'expired');
  const lateEvent={...event,orderCode:Number(late.transferContent.slice(4)),reference:'test-late'};
  await request('/api/payments/webhook','POST',{data:lateEvent,signature:sign(lateEvent)});
  const review=(await request('/api/checkout/lookup','POST',{id:lateCheckout.id,token:lateCheckout.token})).body.data;
  assert.equal(review.state,'review');assert.equal(review.items[0].status,'pending','late payment cannot reserve an expired booking');
  for(const i of payment.items) if(i.productSlug==='zero-test') await request('/api/admin/rental-requests','PATCH',{id:i.id,action:'cancel'});
  const zeroCheckout={...checkout,id:randomUUID(),phone:'0907654323',items:[checkout.items[1]]};
  const zero=(await request('/api/checkout','POST',zeroCheckout)).body.data;
  assert.equal(zero.amount,0);assert.equal(zero.state,'manual');assert.equal(zero.items[0].status,'pending');
  await request('/api/admin/rental-requests','PATCH',{id:zero.items[0].id,action:'confirm'});
  assert.equal((await request('/api/checkout/lookup','POST',{id:zeroCheckout.id,token:zeroCheckout.token})).body.data.state,'confirmed');
  await request('/api/admin/rental-requests','PATCH',{id:zero.items[0].id,action:'cancel'});
  assert.equal((await request('/api/checkout/lookup','POST',{id:zeroCheckout.id,token:zeroCheckout.token})).body.data.state,'cancelled');
  const partialCheckout={...checkout,id:randomUUID(),phone:'0907654324'};
  const partial=(await request('/api/checkout','POST',partialCheckout)).body.data;
  await request('/api/admin/rental-requests','PATCH',{id:partial.items[0].id,action:'cancel'});
  const partialResult=(await request('/api/checkout/lookup','POST',{id:partialCheckout.id,token:partialCheckout.token})).body.data;
  assert.equal(partialResult.state,'review','do not show stale transfer instructions after part of the manual checkout was cancelled');
  assert.equal(partialResult.checkoutUrl,null);
  await request('/api/admin/products','DELETE',{codes:[zeroProduct.code]});
  await request('/api/admin/products','DELETE',{codes:[product.code]});
  await request('/api/auth/session','DELETE');
  await request('/api/admin/products','GET',undefined,401);
  for(let i=0;i<5;i++)await request('/api/auth/session','POST',{identifier:'test@example.com',password:'wrong'},401);
  await request('/api/auth/session','POST',{identifier:'test@example.com',password:'wrong'},429);
  console.log('PASS PHP API: migrations, auth/CSRF, catalog, rental concurrency, checkout price/idempotency/token, zero deposit, signed webhook/replay/late payment, cancellation, logout.');
} finally {
  for (const server of servers) {
    if (server.exitCode === null) { server.kill(); await new Promise(resolve => server.once('exit', resolve)); }
  }
  setup('drop');
  await rm(privateDir, {recursive:true,force:true});
}
